INSERT INTO USERS(LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, MIDDLE_NAME, PASSPORT, MOBILE_PHONE, ROLE)
VALUES ('qwe', '$2a$10$ByXXAs0sCoDlcnhwkyR7U.cg5UVRa9B12ZQovtPajTa7aTXqFts8q', 'Vitaliy', 'Kairachka', 'Alekseevich',
        '1', '1', 'USER')